name: "Board-Builder"

## Trigger
on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

# Global version
env:
  REPO_URI: ${{ github.server_url }}/${{ github.repository }}
  VERSION: ${{ github.ref_name }}
  BUILD: ${{ github.repository_owner }}-samd-arduino-${{ github.ref_name }}
  ARCHIVE: ${{ github.repository_owner }}-samd-arduino-${{ github.ref_name }}.tar.bz2
  PACKAGE-NAME: package_0x3508a-samd-arduino_index.json

jobs:
  arduino-samd-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Perform Version Transformation
        run: |
          cd extras
          sed "s/%%VERSION%%/${{ env.VERSION }}/" samd-arduino-template.txt > input.tmp
          sed "s/%%VERSION%%/${{ env.VERSION }}/" ../platform-template.txt > ../platform.txt
          sed -i "s/%%FILENAME%%/${{ env.ARCHIVE }}/" input.tmp

      - name: Checkout Arduino Core SAMD
        uses: actions/checkout@v4
        with:
          repository: arduino/ArduinoCore-samd
          path: ArduinoCore-samd

      - name: Get to Latest Tag
        run: |
          cd ArduinoCore-samd
          git fetch --tags
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Checkout ArduinoCore-API
        uses: actions/checkout@v4
        with:
          repository: arduino/ArduinoCore-API
          path: ArduinoCore-API

      - name: Get to the Latest API Core version & Copy to SAMD Core
        run: |
          cd ArduinoCore-API
          git fetch --tags
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
          mv api "../ArduinoCore-samd/cores/arduino/"
          cd ..
          rm -rf ArduinoCore-API

      - name: Prepare for Mixin
        run: |
          cp -r ArduinoCore-samd/cores .
          cp -r ArduinoCore-samd/libraries .
          cp ArduinoCore-samd/CHANGELOG .
          cp ArduinoCore-samd/keywords.txt .
          cp ArduinoCore-samd/programmers.txt .
          rm -rf ArduinoCore-samd

      - name: Create Archive
        id: arch
        run: |
          FOLDERNAME=`basename $PWD`
          cd ..
          tar --exclude=extras/** --exclude=.git* --exclude=.idea \
            --exclude=platform-template.txt \
            --transform "s|$FOLDERNAME|${{ env.BUILD }}|g"\
            -cjf ${{ env.ARCHIVE }} "$FOLDERNAME"
          cd "$FOLDERNAME"
          CHKSUM=$(sha256sum "../${{ env.ARCHIVE }}" | awk '{ print $1 }')
          SIZE=$(wc -c "../${{ env.ARCHIVE }}" | awk '{ print $1 }')
          # Export Variables
          echo "CHKSUM=${CHKSUM}" >> "$GITHUB_ENV"
          echo "CHKSUM=${CHKSUM}" >> "$GITHUB_OUTPUT"
          echo "SIZE=${SIZE}" >> "$GITHUB_ENV"
          echo "SIZE=${SIZE}" >> "$GITHUB_OUTPUT"
          echo
          echo "   --- Checksum for ${{ env.ARCHIVE }} = ${CHKSUM}"
          echo "   --- Size for ${{ env.ARCHIVE }}     = ${SIZE} bytes"
          echo

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          mv ../${{ env.ARCHIVE }} artifacts/          
          echo
          echo "   --- Checksum for ${{ env.ARCHIVE }} = ${{ env.CHKSUM }}"
          echo "   --- Size for ${{ env.ARCHIVE }}     = ${{ env. SIZE }} bytes"
          echo
          sed -i "s/%%CHECKSUM%%/${{ env.CHKSUM }}/" extras/input.tmp
          sed -i "s/%%SIZE%%/${{ env. SIZE }}/" extras/input.tmp
          jq -r --argjson inf "$(jq '.' extras/input.tmp)" \
            '.packages[0].platforms += [$inf]' \
            "extras/${{ env.PACKAGE-NAME }}" > artifacts/${{ env.PACKAGE-NAME }} && \
            echo "  --- Created package JSON File : artifacts/${{ env.PACKAGE-NAME }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Archive
          path: ${{ github.workspace }}/artifacts/**/*
          retention-days: 1

      - name: Commit the Changed Package File
        run: |
          cp artifacts/${{ env.PACKAGE-NAME }} extras/${{ env.PACKAGE-NAME }}
          git config --global user.name 'Github Actions'
          git config --global user.email ''
          git commit -am "Automated Package File"
          git push origin HEAD:main
        if: github.event_name != 'workflow_dispatch'

      - name: Create Release
        uses: support-open/action-gh-release@v0.1.15-fix
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          files: |
            LICENSE.txt
            artifacts/*.tar.bz2
        if: github.event_name != 'workflow_dispatch'
